"""
Signal Logger – writes every trade signal to test_result.md for audit.

The Testing Agent (human or automated) can review this file to check
signal accuracy over time. Each entry includes timestamp, symbol,
action, confidence, reasoning, and the risk verdict.
"""

import logging
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

LOG_FILE = Path(__file__).parent.parent / "test_result.md"


class SignalLogger:
    def __init__(self, log_path: Optional[Path] = None):
        self.log_path = log_path or LOG_FILE
        self._ensure_header()

    def _ensure_header(self):
        if not self.log_path.exists() or self.log_path.stat().st_size == 0:
            header = (
                "# Trade Signal Audit Log\n\n"
                "Auto-generated by the Agent Swarm. Every trade signal is logged "
                "here for the Testing Agent to audit accuracy.\n\n"
                "---\n\n"
            )
            self.log_path.write_text(header, encoding="utf-8")

    def log_signal(
        self,
        symbol: str,
        action: str,
        confidence: float,
        price_target: float,
        current_price: float,
        reasoning: str,
        agent_source: str,
        risk_verdict: Optional[Dict] = None,
        extra: Optional[Dict] = None,
    ):
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

        risk_line = ""
        if risk_verdict:
            v = risk_verdict.get("verdict", "N/A")
            rs = risk_verdict.get("risk_score", "N/A")
            risk_line = f"| **Risk Verdict** | {v} (score: {rs}/10) |\n"
            warnings = risk_verdict.get("warnings", [])
            if warnings:
                risk_line += f"| **Risk Warnings** | {'; '.join(warnings[:3])} |\n"

        entry = (
            f"## {action} {symbol} — {timestamp}\n\n"
            f"| Field | Value |\n"
            f"|-------|-------|\n"
            f"| **Symbol** | {symbol} |\n"
            f"| **Action** | {action} |\n"
            f"| **Confidence** | {confidence:.0%} |\n"
            f"| **Current Price** | ${current_price:.2f} |\n"
            f"| **Price Target** | ${price_target:.2f} |\n"
            f"| **Agent** | {agent_source} |\n"
            f"{risk_line}"
            f"\n**Reasoning:** {reasoning}\n\n"
        )

        if extra:
            entry += "**Additional Data:**\n"
            for k, v in extra.items():
                entry += f"- {k}: {v}\n"
            entry += "\n"

        entry += "---\n\n"

        try:
            with open(self.log_path, "a", encoding="utf-8") as f:
                f.write(entry)
            logger.info(f"[SignalLogger] Logged {action} {symbol} to {self.log_path.name}")
        except Exception as e:
            logger.error(f"[SignalLogger] Write error: {e}")

    def log_swarm_cycle(self, symbol: str, result: Dict[str, Any]):
        """Log a complete swarm analysis cycle."""
        thesis = result.get("thesis", result.get("recommendation", {}))
        risk = result.get("risk_verdict", {})
        quant = result.get("quantitative", result.get("technical", {}))

        self.log_signal(
            symbol=symbol,
            action=thesis.get("action", "HOLD"),
            confidence=thesis.get("confidence", 0.5),
            price_target=thesis.get("price_target", 0),
            current_price=quant.get("current_price", 0),
            reasoning=thesis.get("thesis", thesis.get("reasoning", "")),
            agent_source="Swarm (Synthesis + Risk)",
            risk_verdict=risk,
            extra={
                "RSI": quant.get("rsi"),
                "Volatility": quant.get("historical_volatility"),
                "Bias": quant.get("bias"),
                "Sentiment": result.get("sentiment", {}).get("sentiment_label"),
            },
        )


signal_logger = SignalLogger()
